# Generated by Django 3.2.9 on 2021-11-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ymti',
            name='concn',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ymti',
            name='food_cat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ymti',
            name='mate_blood',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ymti',
            name='mbti_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ymti',
            name='mem_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ymti',
            name='mem_birth_ddi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ymti',
            name='mem_loc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ymti',
            name='mem_sex',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ymti',
            name='pf_ins_yn',
            field=models.TextField(null=True),
        ),
    ]
