# Generated by Django 3.2.9 on 2021-11-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_auto_20211111_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='ymti',
            name='mem_no',
            field=models.IntegerField(null=True),
        ),
    ]
